### ISSUE TITLE
Unable to add repo through Home Assistant

### ISSUE THREAD

**Issue by lleidr** [RobertD502/home-assistant-flair#1]
I suspect it's because it's missing the repository file described here: https://developers.home-assistant.io/docs/add-ons/repository/

Here are the errors from the home assistant log:

21-04-22 16:14:21 ERROR (MainThread) [supervisor.store] https://github.com/RobertD502/home-assistant-flair is not a valid add-on repository
21-04-22 16:14:21 INFO (MainThread) [supervisor.resolution.module] Create new issue IssueType.CORRUPT_REPOSITORY - ContextType.STORE / e5cc386e
21-04-22 16:14:21 INFO (MainThread) [supervisor.resolution.module] Create new suggestion SuggestionType.EXECUTE_REMOVE - ContextType.STORE / e5cc386e
21-04-22 16:14:21 WARNING (MainThread) [supervisor.store.data] No repository information exists at /data/addons/git/e5cc386e
21-04-22 16:14:23 INFO (MainThread) [supervisor.store] Loading add-ons from store: 66 all - 0 new - 0 remove
21-04-22 16:14:23 INFO (MainThread) [supervisor.resolution.fixups.store_execute_remove] Remove invalid Store: e5cc386e
21-04-22 16:14:23 INFO (MainThread) [supervisor.store.git] Removing custom add-on repository https://github.com/RobertD502/home-assistant-flair
21-04-22 16:14:23 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING
21-04-22 16:14:23 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.PWNED/ContextType.ADDON
21-04-22 16:14:23 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.FREE_SPACE/ContextType.SYSTEM
21-04-22 16:14:23 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.SECURITY/ContextType.CORE
21-04-22 16:14:23 INFO (MainThread) [supervisor.resolution.check] System checks complete
21-04-22 16:14:23 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING
21-04-22 16:14:23 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete

**Comment by RobertD502** [comment]
I believe you're trying to add the repo through the Home Assistant supervisor tab. The repo can only be added through HACS (Home Assistant Community Store).

**Comment by lleidr** [comment]
I successfully added it through HACS. Thank you.

**Comment by RobertD502** [comment]
Glad you got it working!
