### ISSUE TITLE
Flair authentication failed. Are your credentials correct?

### ISSUE THREAD

**Issue by mclever** [RobertD502/home-assistant-flair#11]
Getting Flair authentication failed. Are your credentials correct?

Tried both version of the creds that were provided by Flair and neither worked.

Anyone else having this issue on the latest HA release?

Only thing I see even with logs on debug for custom_components.flair is

2021-11-19 08:54:11 ERROR (MainThread) [custom_components.flair.config_flow] Unable to connect to Flair: Failed to Log In
2021-11-19 08:54:11 ERROR (MainThread) [custom_components.flair.config_flow] 'access_token'

sometimes when closing the connect i get this, but only show up in log after closing the connection/creds window
2021-11-19 10:52:44 ERROR (MainThread) [custom_components.flair.config_flow] Unable to connect to Flair: Failed to Log In
2021-11-19 10:52:44 ERROR (MainThread) [custom_components.flair.config_flow] ApiError<HTTP Response: 404>

**Comment by mclever** [comment]
I reached out to Flair support and they confirmed that the creds are good using curl and API is functioning as expected with no change to OAuth recently.

**Comment by RobertD502** [comment]
I can confirm that the integration works on the most recent HA version.

Just to confirm, are you using your normal credentials to log in or are you using credentials that are specific to the API (credentials that you need to separately request from flair)?

**Comment by mclever** [comment]
I got two sets of API creds from Flair, OAth 2 and 1. Neither work.

**Comment by RobertD502** [comment]
This integration uses OAuth1 credentials (which you have). I can try investigating what is going on in your situation if I have your OAuth1 credentials (I've helped other users track down problems that were specific to just them this way). If you drop a preferred email address here, I can contact you to keep the credentials secret.

**Comment by mclever** [comment]
mclever at hotmail.com

**Comment by mclever** [comment]
FYI for others. Robert has helped identify that I have some "phantom rooms and structures" that Flair support needs to remove. Will update on Monday when support gets back to me.

This came from the bad Flair puck setup process on my Android that required location access to fully complete the setup so I had to run through it a few times.

**Comment by mclever** [comment]
Still no word from flair support, bad timing with thanksgiving I guess. @RobertD502 , is there a way for the integration to detect the phantom location and ignore it?

**Comment by RobertD502** [comment]
I just pushed an update that gets around the phantom structures and rooms problem.

Be sure to update the Flair Home Assistant integration to the latest version (`0.0.4.4`) and use your `OAuth1` credentials to set up the integration.

**Comment by mclever** [comment]
Works perfect, thank you!
