### ISSUE TITLE
Ambient Light

### ISSUE THREAD

**Issue by sstarcher** [RobertD502/home-assistant-flair#12]
The pucks say they have ambient light sensors.  It would be useful to expose.

**Comment by RobertD502** [comment]
So, the [official API](https://documenter.getpostman.com/view/5353571/TzsbKTAG#95f3da1f-99f0-4bce-a8e5-0031ebab4fa8) doesn't return ambient light data. However, I did notice that the app history graphs do return that data, but I'll have to sniff out the requests from the app before adding that.

**Comment by RobertD502** [comment]
The latest release (0.0.4.3) creates light level sensor entities for any pucks that you may have.

**Comment by sstarcher** [comment]
Well played as I was just talking to them https://support.flair.co/hc/en-us/community/posts/4414165521293-Flair-API-Ambient-Light-Support
