### ISSUE TITLE
'NoneType' object is not subscriptable error during Setup

### ISSUE THREAD

**Issue by mgrose** [RobertD502/home-assistant-flair#16]
Hello - I am getting an error after entering API keys on setup.  It spins for a little bit and then logs this:

Logger: custom_components.flair.config_flow
Source: custom_components/flair/config_flow.py:67
Integration: Flair ([documentation](https://github.com/RobertD502/home-assistant-flair/blob/main/README.md), [issues](https://github.com/RobertD502/home-assistant-flair/issues))
First occurred: 11:28:50 AM (2 occurrences)
Last logged: 11:47:36 AM

Error occured during Flair setup: 'NoneType' object is not subscriptable

**Comment by RobertD502** [comment]
Is anything else logged?

**Comment by mgrose** [comment]
I switched to debug logging and still that's the only log entry I can find.  In Flair, I have 3 pucks.  1 tied to an Ecobee thermostat through that built-in integration, and the other 2 connected to minisplits as IR controllers.  I tried removing the Ecobee integration and also just tried resetting all the pucks and creating a new home, setting it as default.  Same exact error still.

**Comment by RobertD502** [comment]
Within the Flair app, do you have Rooms set up?

**Comment by mgrose** [comment]
Yes 3 rooms, 1 for each puck.

**Comment by RobertD502** [comment]
What's the best e-mail to reach you at?

**Comment by mgrose** [comment]
michael (at) mgrose.com

**Comment by RobertD502** [comment]
Issue due to phantom HVAC unit.
Resolved in version 0.0.5.1
