### ISSUE TITLE
Bump oAuth version to oAuth2

### ISSUE THREAD

**Issue by ErnestStaug** [RobertD502/home-assistant-flair#19]
Hello,

It seems that this integration is using oAuth 1.0 flair.co says it's legacy and out of date, would be nice if we could switch to oAuth2.

**Comment by RobertD502** [comment]
This uses a library created by Flair that uses OAuth1. So, a change to OAuth2 won't happen until Flair has completed transitioning their python library to OAuth2.

**Comment by ErnestStaug** [comment]
Noted. Weird that they put oAuth1 as legacy but still have not updated their python Lib.
