### ISSUE TITLE
Think its possible to get vent current readings?

### ISSUE THREAD

**Issue by Budman17r** [RobertD502/home-assistant-flair#2]
```
GETVent Current Reading
https://api.flair.co/api/vents/53d69ae0-59d4-5de0-4a86-4d468cacda63/current-reading
The Vent endpoint will have a link to the Vent current-reading endpoint. Here you will find the latest set of sensor readings for this device, with information such as:

created_at: date and time of this reading, in GMT
duct-temperature-c: the temperature read by this Vent, in Celsius
duct-pressure: the pressure read by this Vent, in kPA
percent-open: the status of this Vent (100 refers to 100% open, 0 refers to closed)
system-voltage: the battery voltage, in V
rssi: the 915MHz radio signal strength
AUTHORIZATION
OAuth 2.0
Access Token
```
https://documenter.getpostman.com/view/5353571/Rzfnj6YR#c0066ce0-709a-494a-8bdc-749a0c5b2f2f

**Comment by RobertD502** [comment]
Yes. All of those, except the pressure and duct temperature, are already included as attributes for vent entities. I didn't include duct temp or pressure as to not go overboard with the attributes especially with ones that I highly doubt users would use.

**Comment by Budman17r** [comment]
Oh I get ya, I'm just wanting to monitor the duct pressure/Temp to see track the benefits of the flair vent, and pulling it to outside sources from ha

**Comment by RobertD502** [comment]
I see. I'm not sure how much you'll get out of duct temp/pressure. I'm sure you're aware already- you can see trends for those through the flair app.

**Comment by Budman17r** [comment]
Ohh I understand, I just wanted to offload it to another data visualization engine, to have longer and better visualizations. I'm trying to determine how much it helps.   If that makes sense.  I appreciate you talking to me though!

**Comment by RobertD502** [comment]
If you're trying to see how much the flair vents help, I'd focus on room temperatures that the flair vents are in. You're not going to get much insight into how well the flair vents are doing themselves by seeing that your duct temp is 125F when heating, for example. No need to thank me- questions are always welcome.

**Comment by Budman17r** [comment]
Ya and I am tracking that. Mostly trying to MO it or the differences in
duct pressure against the furnace as well. To see if I can detect a
potential failure.

I also understand data logging from home assistant for this prolly isn't
terribly efficient.

**Comment by RobertD502** [comment]
Can't knock you for wanting more data. Do you have a temp gauge inside the furnace to track temp directly at the furnace?

**Comment by Budman17r** [comment]
No not yet. I've been thinking about getting a remote longer as well. For a
monometer to keep track of the internal pressures. Flair has done my house
really well on keeping the Temps right with ecobee. But I want to prove
people wrong who says it damages furnace.

Todd

**Comment by RobertD502** [comment]
Just link them to the study that Flair's logic is based off of.

**Comment by RobertD502** [comment]
Duct Temp and Pressure added in latest release 0.0.3
