### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by ErnestStaug** [RobertD502/home-assistant-flair#21]
Hello,

Vents suddenly stopped working on home assistant.

```
Logger: homeassistant.components.select
Source: helpers/entity_platform.py:719
Integration: Select (documentation, issues)
First occurred: 20 April 2022, 00:39:56 (5612 occurrences)
Last logged: 20:56:34

Updating flair select took longer than the scheduled update interval 0:00:30
```

<img width="754" alt="image" src="https://user-images.githubusercontent.com/17262977/164769284-eba5782c-243e-4bec-b63a-797605fb974d.png">

**Comment by RobertD502** [comment]
Happening for me as well. I have a few other logs that are indicating server side issues (504 codes). Unfortunately, not something I can fix within the integration.

**Comment by ErnestStaug** [comment]
Probably API issue... that's not good. We need local integration

**Comment by RobertD502** [comment]
Can confirm it is on their end. Just restarted Home Assistant and was immediately met with a 504 code from their servers.

**Comment by Spross1** [comment]
it looks like flair fixed their api. I had to restart Home Assistant but everything is working now for me

**Comment by RobertD502** [comment]
504 responses continue to occur much more frequently than usual. I've contacted the engineering team, but most likely won't hear back until this week. Will keep everyone posted.

**Comment by Drulzy** [comment]
yeah it's not just HA... Flair is barely communicating with ecobee at the moment. Calls for heat, then forgets to end the call... doesn't open vents it should... If I were a smart guy I'd want to end the cloud reliance... :(

**Comment by ErnestStaug** [comment]
![F02A470A-1057-45E7-8D16-C11A073EDFBC](https://user-images.githubusercontent.com/17262977/165225267-6cf36010-2c13-4ec8-a27d-93f8ac89414d.jpeg)

they increased server count, but It does not seem to fix the problem, and no local solution will be provided… I’ve ordered some esp32 will try to change their vent “brains”, as this cloud stuff doesn’t do it for me.

**Comment by RobertD502** [comment]
Can anyone else confirm seeing 401 status errors after a while?

**Comment by Spross1** [comment]
I don't see that in my logs, but I do see this "Updating flair sensor took longer than the scheduled update interval 0:00:30" for both the "homeassistant.components.sensor" as well as the "homeassistant.components.select" in my logs and I don't think this was as prevalent in the past and it is popping up every 60 seconds

> Can anyone else confirm seeing 401 status errors after a while?

**Comment by RobertD502** [comment]
> I don't see that in my logs, but I do see this "Updating flair sensor took longer than the scheduled update interval 0:00:30" for both the "homeassistant.components.sensor" as well as the "homeassistant.components.select" in my logs and I don't think this was as prevalent in the past and it is popping up every 60 seconds
> 
> > Can anyone else confirm seeing 401 status errors after a while?

Can you click on the log items and see if anything else is reported such as status codes (504, 401, etc).

**Comment by Spross1** [comment]
> > I don't see that in my logs, but I do see this "Updating flair sensor took longer than the scheduled update interval 0:00:30" for both the "homeassistant.components.sensor" as well as the "homeassistant.components.select" in my logs and I don't think this was as prevalent in the past and it is popping up every 60 seconds
> > > Can anyone else confirm seeing 401 status errors after a while?
> 
> Can you click on the log items and see if anything else is reported such as status codes (504, 401, etc).

Sorry, Robert, that was all of the information reported in the log as I was using the file editor to review the logs and I'm unable to click those. But I took a screenshot of the log entry that I can click on for reference in the UI.
<img width="528" alt="Screen Shot 2022-04-28 at 7 30 19 PM" src="https://user-images.githubusercontent.com/87457720/165868511-99a0364b-3211-4e28-a5fe-aa4becfa5ca5.png">

**Comment by RobertD502** [comment]
@Spross1 I have released a pre-release of `0.0.5.6` which uses an updated version of the backend library and is faster - this may cut out some of these warning messages for you. However, since the release includes code changes that are specific to Home Assistant 2022.5.0, it is only available to those who are running the beta version of 2022.5.0. Once 2022.5.0 is officially released, it will be available to everyone.

**Comment by Spross1** [comment]
> @Spross1 I have released a pre-release of `0.0.5.6` which uses an updated version of the backend library and is faster - this may cut out some of these warning messages for you. However, since the release includes code changes that are specific to Home Assistant 2022.5.0, it is only available to those who are running the beta version of 2022.5.0. Once 2022.5.0 is officially released, it will be available to everyone.

How do I get access to the pre-release? If I can’t right now no worries but I’m currently running Version | core-2022.5.0b2 and I don’t see an update in HACS or anywhere else. I unfortunately I don’t know how to check the version of the integration I have though

**Comment by RobertD502** [comment]
@Spross1 Go to HACS --> Integrations, Scroll down to the Flair integration and press on the overflow menu (three dots) and select `redownload`:

![image](https://user-images.githubusercontent.com/52541649/165878140-ca22dde7-0fb1-46d7-a6d0-01ac0b6c5830.png)


Make sure `Show beta versions` is checked:

![image](https://user-images.githubusercontent.com/52541649/165878196-f669de94-44a7-4fea-89c6-4499f1e13100.png)

There is a weird bug in HACS where it won't let you download the latest beta version from this screen when initially checking show beta versions, but if you exit out of that screen (after checking show beta versions), you should see the Flair card within HACS now highlighted in blue with the option to update.

**Comment by Spross1** [comment]
@RobertD502 ok yes I see that now thank you for that information. By the way, I don't think that's a bug, it did load for me, it just took a few seconds while it was blacked out, then it loaded the beta option. I just downloaded it and I'm restarting so I'll try it out. Thank you for your work on this integration by the way, I love it!

**Comment by RobertD502** [comment]
Flair seems to have resolved their server side issues. I have also changed 0.0.5.6 from pre-release to a regular release (requires HA 2022.5.0) which includes speed improvements. Restarting HA should get HACS to show the release if it isn’t showing already. With all of that said, I will be closing this issue now.
