### ISSUE TITLE
Type error during setup

### ISSUE THREAD

**Issue by bfenty** [RobertD502/home-assistant-flair#23]
While trying to setup Flair I'm receiving the following error on Home Assistant, which appears to be related to mismatched types. This occurred after entering my ID and Secret for the Flair API. 

`This error originated from a custom integration.

Logger: custom_components.flair.config_flow
Source: custom_components/flair/config_flow.py:67 
Integration: Flair (documentation, issues) 
First occurred: 9:27:28 AM (1 occurrences) 
Last logged: 9:27:28 AM

Error occured during Flair setup: can only concatenate str (not "NoneType") to str `

**Comment by RobertD502** [comment]
I'm still to this day ironing out random issues with how Flair handles old setups made within their app. Needless to say, if you could shoot an e-mail to FlairHass at gmail dot com we can work on determining what within your account is/are the culprit(s) as it differs from person to person.

**Comment by bfenty** [comment]
Will do. Thanks for the support.

**Comment by RobertD502** [comment]
Error caused by use of OAuth 2.0 credentials instead of 1.0.
