### ISSUE TITLE
Error loading integration in Home Assistant due to missing flair_api module

### ISSUE THREAD

**Issue by fcfort** [RobertD502/home-assistant-flair#27]
Seeing the following error in Home Assistant for the Flair integration:

>Error importing platform config_flow from integration flair to set up flair configuration entry: No module named 'flair_api'

The `flair_api` import used to come from here: https://github.com/flair-systems/flair-api-client-py/blob/d928840eab96eb80c9c5069ddf64e6841a0e2f60/flair_api/__init__.py#L7

Before the dependency was switched to https://github.com/RobertD502/flair-api-client-py.

**Comment by RobertD502** [comment]
What version of this integration are you on? The latest release that I pushed out uses a new version of `hass-flair-helper` that correctly imports the module.

**Comment by RobertD502** [comment]
Ah wait never mind you're right. I forgot to change the config file

**Comment by RobertD502** [comment]
Fixed in version `0.0.6.0`
