### ISSUE TITLE
Updating flair fan took longer than the scheduled update interval 0:00:30

### ISSUE THREAD

**Issue by sstratoti** [RobertD502/home-assistant-flair#3]
Hi there!

I'm loving this integration, but I find that after a while I can't communicate with flair anymore unless I restart HA.

Is there anything I can add to my logger to troubleshoot?

All I'm seeing is:

Updating flair fan took longer than the scheduled update interval 0:00:30

over and over again. My last restart was 41 hours ago. Once I restart HA, it works as expected.

I can also change my flair vents through their app, but its not registering in HA. So I know my vents are online, its got to be an issue on the HA end of things.

Thanks!

**Comment by RobertD502** [comment]
So I've investigated this and the issue can be due to a wide range of things. For some this was due to network stability issues, too many processes occurring at the same time that their hardware couldn't handle, some reported this issue stemmed from their storage device with I/O problems, and some rpi users tracked it down to not using a sufficient enough power supply. Unfortunately, it doesn't seem problem stems from the Flair integration and looks to be on the HA side of things.

**Comment by sstratoti** [comment]
OK - I'm on an NUC, so I don't think it's power/hardware related.

But! I did see a lot of browser_mod connections hitting the websocket api with bad requests. I attempted to remove it when I was experiencing issues with node red losing its connection to HA via websocket. Once I cleared the cache on all of my browsers (tablet, phone, laptops), the browser_mod errors in the log stopped. I think the browser's cached files were trying to phone home, and the integration no longer existed. 

I cleaned up a bunch of other errors in my log that were lingering. I'm going to let it run for a bit and will report back if I still encounter issues. For now I'm going to close this. Thanks!

**Comment by RobertD502** [comment]
@sstratoti Just to add to this- I've noticed this happen for myself with Flair, but also several other integrations that aren't custom components. Seems that the error is pointing to the problem occurring within Home Assistant, but as I mentioned there can be several causes. When this does happen to me, those components that were logging the error still work hours later so your system might be locking up in some manner. If it does persist, one solution is to set an automation to restart HA every night.
