### ISSUE TITLE
ApiError<HTTP Response: 401> on install

### ISSUE THREAD

**Issue by plapin751** [RobertD502/home-assistant-flair#31]
hi,  trying to install but when i add integration, i get to setup popup and paste in OAuth 1.0 (Legacy): and secret.
getting following error in the log.  tried logging in via local ip and nabu casa 
any suggestions, kina lost. tried OAuth 1.0 & 2 info neither worked.

..

Logger: custom_components.flair.config_flow
Source: custom_components/flair/config_flow.py:44
Integration: Flair ([documentation](https://github.com/RobertD502/home-assistant-flair/blob/main/README.md), [issues](https://github.com/RobertD502/home-assistant-flair/issues))
First occurred: 6:42:11 PM (7 occurrences)
Last logged: 6:51:15 PM

Flair API error occured during setup: ApiError<HTTP Response: 401>
Error occured during Flair setup: 'NoneType' object is not subscriptable

**Comment by RobertD502** [comment]
I'd say hold off for a bit. I am the finish line in terms of rewriting the integration to use a new backend and OAuth 2.0.

If you're eager to use the current integration before then, shoot me an email with your credentials at flairhass at gmail dot com. I'll be able to take a look to see if/what bug on your account is causing the issue.

**Comment by plapin751** [comment]
thank you for the quick response,  i have emailed you the info.

**Comment by RobertD502** [comment]
@plapin751 Pre-Release is live. You can access the update by setting the switch "Show beta versions" to On for the Flair integration within HACS:

![image](https://user-images.githubusercontent.com/52541649/185685475-8fe3dbd3-bd30-46f9-95ed-5a69ae472b90.png)

**Post any bugs/discussion regarding 0.1.0 to the [0.1.0 Discussion](https://github.com/RobertD502/home-assistant-flair/discussions/32).**
