### ISSUE TITLE
Reverse Home Away Hold Example

### ISSUE THREAD

**Issue by slopokdave** [RobertD502/home-assistant-flair#33]
Hello, first thank you for the flair addon. It's working great for us so far!

Can you give an example of code for a button to Reverse Home/Away Hold? I can't get it to work. Thank you!

**Comment by RobertD502** [comment]
I'm not sure I understand. Are you asking for an automation to press the reverse home/away home button?

**Comment by slopokdave** [comment]
I can successfully create a drop down toggle for Home/Away mode, your documentation says an entity type "button" is available to "Reverse home/away hold". I am trying to use this function.

**Comment by RobertD502** [comment]
It is simply a button:

![image](https://user-images.githubusercontent.com/52541649/185762596-9aa469fb-bdb8-4161-8760-dab1d1f7576f.png)

To use the entity you "Press" the button.

**Comment by slopokdave** [comment]
Yes exactly, can you share the code? I am better at reading that to understand how it works. :)

**Comment by RobertD502** [comment]
Ohhhhhhh....yeah the documentation is for the current pre-release. I'm assuming you installed the previous version. If you just added the integration, delete it. Set HACS to show beta versions for the Flair integration. Once you've done that, you'll see the 0.1.0 pre-release.

Note: you need to use your OAuth 2.0 credentials with 0.1.0 NOT OAuth 1.0.

**Comment by slopokdave** [comment]
Got it, it works now! 

One more question, I'm not sure if this is configurable via your addon or if this is due to something else. When I use climate entity, down/up degree is "0.5", how can I change so that it is in "1.0" increments instead? Thanks again.

**Comment by RobertD502** [comment]
What climate entity is it?

**Comment by slopokdave** [comment]
Oh I see now, I am using "custom:simple-thermostat".... my code. I understand if you cannot help, I think it may be something i need to change w/ simple-thermostat? 

`type: grid
square: false
columns: 1
cards:
  - type: custom:simple-thermostat
    entity: climate.dave_s_office_room
    layout:
      step: row
    header: true
    control: false
  - type: entities
    entities:
      - entity: select.dave_s_office_activity_status
        name: Status
    state_color: true`

**Comment by RobertD502** [comment]
I left the Home Assistant defaults which i believe are 1 if dealing with F and 0.5 if dealing with C. Since you're using a custom card, I'd look into the settings of the custom card.

**Comment by slopokdave** [comment]
Thank you for all your help!

**Comment by RobertD502** [comment]
No problem!
