### ISSUE TITLE
v0.1.0 integration need to be reconfigured after each HA restart 

### ISSUE THREAD

**Issue by Spross1** [RobertD502/home-assistant-flair#34]
I got the new oath 2.0 credentials from Flair yesterday and tried the update, but now each time I restart it's asking for these credentials. Nothing in the log to help. It seems that some of the flair devices start loading at least, but I'm still getting the reconfigure prompt after each restart. I'll post what I see in the logs at least for reference since it doesn't look like there are any issues popping up, but I don't know what to add to the config to debug further. I'm going to downgrade for now
<img width="2274" alt="Screen Shot 2022-08-22 at 11 51 10 AM" src="https://user-images.githubusercontent.com/87457720/185975959-c91b0fc9-6ce8-49ed-be84-61fba1babfa8.png">
.

**Comment by RobertD502** [comment]
Did you delete your old Flair configuration from the integrations page and set it up fresh?

**Comment by Spross1** [comment]
Sorry right as I posted the issue I went back to review the v0.1.0 notes and saw you said that. I took the easy route originally but yes this seems to have fixed my issue. Sorry to take up your time. I appreciate your reallyyyy fast response!!

**Comment by RobertD502** [comment]
No problem at all! You caught me at a time I was on my phone and saw the GitHub notification.
