### ISSUE TITLE
Plugin fails to register if user has no vents

### ISSUE THREAD

**Issue by shauntarves** [RobertD502/home-assistant-flair#4]
I submitted a PR in the https://github.com/RobertD502/hass-flair-helper project to handle an exception that's thrown when I try to configure this.

I don't have any vents, but I do have some pucks that I want to use. The entire config flow fails because the `EmptyBodyException` bubbles up to hass.

**Comment by RobertD502** [comment]
Have you tested this out? I won't be able to since I do have vents.

**Comment by shauntarves** [comment]
Hey @RobertD502,

That solution worked for me. The only thing I noticed was this message that seems to be missing some content

![Screen Shot 2021-07-23 at 12 37 34 PM](https://user-images.githubusercontent.com/4731056/126814042-29f8088c-e8ea-44ab-a926-57c9c058447a.png)

**Comment by RobertD502** [comment]
I know exactly what is causing that. Will fix it once I'm back at the computer.

**Comment by RobertD502** [comment]
@shauntarves Just fixed it. Will create a new release as soon as I publish the hass-flair-helper changes to PyPi. Once the new release is out, update through HACS, then delete the integration (from the config --> integrations menu) , reboot, and add the integration again through the config --> integrations menu. The integration should display the title "Flair" on the integrations page as well as show "Flair" in the prompt that follows the initial setup.

**Comment by shauntarves** [comment]
Hey @RobertD502 did you get this release done? I'm not seeing it.

**Comment by RobertD502** [comment]
Just pushed it to PyPi. I've been away from my main Mac where my PyPi key is. Sorry for the delay! Will be pushing out the HA updates as well in a bit.

**Comment by RobertD502** [comment]
Hey @shauntarves do you happen to be using your puck(s) to control any mini-splits?

**Comment by shauntarves** [comment]
@RobertD502 sure am...I was hoping to add that functionality to this plugin.

**Comment by RobertD502** [comment]
Do you have another preferred place of contact besides github?

**Comment by shauntarves** [comment]
Sure.. hit me on email <shaun at tarves dot net> and we can go from there.
