### ISSUE TITLE
Setup confusion

### ISSUE THREAD

**Issue by ahgraber** [RobertD502/home-assistant-flair#41]
Hi there!  I've added the integration through HACS, but when I try to set it up, I get a message:

> ### This device can not be added from the UI
> 
> You can add this device by adding it to your 'configuration.yaml'. See the documentation for more information.

Based on the readme here, it seems as though there is supposed to be setup process through the UI?  If not, is there a sample `configuration.yaml` file I can review?

I should add that prior to installing Flair through HACS, I updated my HomeAssistant instance to 2022.11.1, and have fully restarted Home Assistant, Supervisor, and the rpi host itself.

Thanks!

**Comment by RobertD502** [comment]
This sounds like it is something HACS related as the integration has never had a YAML setup option. I would go into HACS, go to the Flair integration page there, select redownload, then download the latest version. After doing so, go into the custom components folder and make sure the flair folder is there. If you see it there, then restart Home Assistant and go to the Home Assistant integrations page to add the Flair integration.

**Comment by ahgraber** [comment]
Thanks for the fast response!  

I have done as you suggested and redownloaded, confirmed the components, and restarted both HA and the host - same error.  I also completely uninstalled and reinstalled via HACS, restarted/rebooted - same error.

I guess I can wait to try again until Home Assistant and/or HACS bump to a new version?

**Comment by ahgraber** [comment]
I found the issue - I was using a different flair integration and even though I renamed the folder in `custom_components/`, it still overlapped the integration name.  After fully removing the old integration, this one works fine.

Closing this issue.

**Comment by RobertD502** [comment]
Yup renaming won't work if the domain in the manifest is the same!
