### ISSUE TITLE
IR HVAC Units not appearing

### ISSUE THREAD

**Issue by shauntarves** [RobertD502/home-assistant-flair#45]
Hi Robert,

I'm seeing a strange (I think) issue with my HA Flair instance. Please note that I've already deleted and re-installed the Flair integration and there was no change in behavior.

Anyway, all of my pucks (3 of them) are showing up, as well as my rooms and structure. However, the actual IR devices (mainly 3 mini-splits) are NOT being pulled into HA. I've confirmed they are in the Flair app's Home Settings (under both "Zones" and under "Mini Splits, Window Units...").

Is there something that I am missing to get this working? Happy to debug, provide logs, etc.

**Comment by shauntarves** [comment]
I'm an idiot - should have checked the logs first:

```
Last logged: 1:23:45 PM

Flair HVAC Unit Living Room Unit does not have a temperature scale. Contact Flair customer support to get this fixed.
Flair HVAC Unit Kitchen Unit does not have a temperature scale. Contact Flair customer support to get this fixed.
Flair HVAC Unit Basement Unit does not have a temperature scale. Contact Flair customer support to get this fixed.
```

**Comment by RobertD502** [comment]
I pointed this problem out to them a while back after which they realized some of their IR code sets didn't have a temp scale defined and said they'd fix it. Looks like yours was not one of the ones fixed.
