### ISSUE TITLE
Can't Graph current thermostats values

### ISSUE THREAD

**Issue by roberthau1981** [RobertD502/home-assistant-flair#47]
We have 3 thermostats in the house.

The thermostat card shows the current value, but i can't graph the value anywhere.

I'm using a nest 3rd gen and 2 honeywell d6 pro's1

![Uploading image.png…]()

**Comment by roberthau1981** [comment]
BTW i love the flair integrated into homekit.

**Comment by RobertD502** [comment]
I'm unable to see what image you're attempting to upload (it wasn't uploaded).

**Comment by RobertD502** [comment]
What entity are you using? (The climate entity from your structure, room, etc)

**Comment by RobertD502** [comment]
I'm unable to see anything. All of your replies are coming in like this:

![image](https://user-images.githubusercontent.com/52541649/212133826-fc3465c0-fe98-4ef8-a0ea-f6c43d3b210a.png)

Switch over to the github site to upload images/reply.

**Comment by roberthau1981** [comment]
![flair1](https://user-images.githubusercontent.com/23276932/212135583-cd23bd52-0158-4b7a-adb0-a1f4b4c498e6.png)
![flair2](https://user-images.githubusercontent.com/23276932/212135586-1c4df8d1-80c2-482b-a88a-3b023c1ef277.png)
![flair3](https://user-images.githubusercontent.com/23276932/212135588-e74f4ba5-02bb-4d3a-a61e-3176baaee592.png)

**Comment by RobertD502** [comment]
What card are you using in Home Assistant to display the graph?

Also, can you please provide pictures of each of the rooms that aren't showing up in the graph --> Provide images from the Flair integration screen for each room that shows all entities associated with each room. For example:

![image](https://user-images.githubusercontent.com/52541649/212137526-b142b834-0983-419c-8555-d45582aa006b.png)

**Comment by RobertD502** [comment]
Also please provide the YAML code that you have for the graph card you are using. You can do that by editing the card and selecting "SHOW CODE EDITOR", which will show the YAML being used to create the card.

**Comment by roberthau1981** [comment]
This is the multiple Graphs.

type: custom:plotly-graph
entities:
  - entity: sensor.dining_room_268e_temperature
  - entity: sensor.living_room_d7ca_temperature
hours_to_show: 24
refresh_interval: 10


**This is a sample thermostat**
type: thermostat
entity: climate.hallway_room

**Comment by RobertD502** [comment]
From what I can see in the YAML, your graph card doesn't have the climate entities for the 3 Flair rooms you're missing defined. Since the Flair room climate entities are climate entities and not sensors, you will also need to define the attribute that you want to plot for each one of them (as shown in the plotly-graph documentation). For example, if I want to plot the current temperature for my Flair dinning, bedroom, and office rooms, the YAML would look like this:

```
type: custom:plotly-graph
entities:
  - entity: climate.dining_room_room
    attribute: current_temperature
  - entity: climate.bedroom_room
    attribute: current_temperature
  - entity: climate.office_room
    attribute: current_temperature
hours_to_show: 24
refresh_interval: 10
```

What you end up with is this:

![image](https://user-images.githubusercontent.com/52541649/212144357-3d1ccce3-aecf-4822-b533-32efd1112d5d.png)

**Comment by roberthau1981** [comment]
your awesome that was the fix.
