### ISSUE TITLE
Vent temperature

### ISSUE THREAD

**Issue by tsuckow** [RobertD502/home-assistant-flair#51]
The vent temperature appears to be treated as unsigned so when the temperature goes below freezing (don't ask) home assistant claims the temperature is thousands of degrees.

**Comment by RobertD502** [comment]
I'm not sure this is something that I can address as the temperature conversion/presentation is being handled by home assistant.

As you can see [here](https://github.com/RobertD502/home-assistant-flair/blob/e526188a7f437e1cfeb74a730f31abcede550ff2/custom_components/flair/sensor.py#L694), the native value sent from Flair is in Celsius which I reference in the native unit of measurement. Home Assistant then handles converting/not converting based on the user's units defined in Home Assistant.

Out of curiosity, would you be able to send a request to Flair's API when you notice this is happening and see what value Flair is reporting for the duct temp? Perhaps the issue originates from their end.

**Comment by tsuckow** [comment]
![Screenshot_20230223-115817.png](https://user-images.githubusercontent.com/262439/221016754-ab8c8431-1ec5-4676-99d2-a417585a7d79.png)

It isn't the API but this is their app which appears to imply a signed 16bit number is used to store the temperature in 100ths of a degree c.

**Comment by RobertD502** [comment]
Their app uses their API. This alone shows me that the issue is originating on their end. I'd send customer support a message with that screenshot.
