### ISSUE TITLE
Request to publish releases to flair.zip

### ISSUE THREAD

**Issue by ptr727** [RobertD502/home-assistant-flair#57]
Hi, thank you again for you custom component.

May I please request you publish via releases and not via the main branch.  
Publishing to a targeted release would allow my ansible deployments to pickup a flair.zip.  
It would also you to change your hacs manifest to use releases.

Yes, I know there is a release, but it is an auto release and as such it does not get a permalink that auto translates latest to a static target filename.

E.g. consider the following that publish using the domain name:  
hacs: `https://github.com/hacs/integration/releases/latest/download/hacs.zip`
hass-vantage: `https://github.com/loopj/hass-vantage/releases/latest/download/vantage.zip`

Vs. needing pull from main branch without knowing that it is a release or not:  
flair: `https://github.com/RobertD502/home-assistant-flair/archive/refs/heads/main.zip`

**Comment by RobertD502** [comment]
No problem, I'll add it to the workflow.

**Comment by ptr727** [comment]
Looks like the release has not been pushed yet?

`https://github.com/RobertD502/home-assistant-flair/latest/download/flair.zip` is 404?

**Comment by RobertD502** [comment]
Correct. It gets pushed when a new release is created.

**Comment by ptr727** [comment]
Ok, but do keep in mind you already updated hacs.json, so hacs will also be looking for the release, just like I did, and may fail unless the flair.zip is present.  
Maybe manually run the action to push the same release version but to flair.zip?

**Comment by RobertD502** [comment]
Just tested in HACS and it doesn't look for the zip yet since the changes aren't reflected until the next release.

I'll have to go edit the workflow to manually dispatch. Will report back.

**Comment by RobertD502** [comment]
Only way was to publish a new release. 0.1.8.3 should have flair.zip.

**Comment by ptr727** [comment]
Thank you, confirmed it is present, I deploy using Ansible and I can now use your release zip.
