### ISSUE TITLE
Overriding room active/inactive is a great idea

### ISSUE THREAD

**Issue by Drulzy** [RobertD502/home-assistant-flair#7]
Alexa can do this with native Flair integration with "turn off <thermostat name>" so it should be doable with your scripts. I tried to parse your script and the flair API, but it's gobbledegook to me, sorry I can't help. 

I'm not sure how HA would expose it to Alexa, so "Turn ON/OFF" should work, but she might balk with "set active/inactive" as she doesn't like some verbs for some reason. I guess that's abstracted by HA, so it's not something you set anyway?

There's some great custom thermostat tiles which would be awesome with a simple on/off button and the temp controls. 

Sorry if this issues are the wrong way to offer encouragement, this integration is awesome.

**Comment by RobertD502** [comment]
@Drulzy Setting the room to Active/Inactive has been introduced as a select entity in 0.0.5.0.

**Comment by usingapc** [comment]
I'm probably missing something simple but I can't find a way to change the select entities(Active/Inactive) via a script of automation.  Can anyone point me in the right direction?  I assumed I would call a service like **input_select** but these select entities are not valid for that service time.  I found **Home Assistant Core Integration: Generic turn on** works to set them to active but **Home Assistant Core Integration: Generic turn off** does not.

**Comment by RobertD502** [comment]
> I'm probably missing something simple but I can't find a way to change the select entities(Active/Inactive) via a script of automation.  Can anyone point me in the right direction?  I assumed I would call a service like **input_select** but these select entities are not valid for that service time.  I found **Home Assistant Core Integration: Generic turn on** works to set them to active but **Home Assistant Core Integration: Generic turn off** does not.

This can be done using the "select.select_option" service. The input_select service isn't used for select entities.

Just a heads up, general questions should be posted in the integration's [Home Assistant Community thread](https://community.home-assistant.io/t/custom-component-flair-control-vents-and-rooms/301788). You had no way of knowing as I forgot to mention this in the documentation.
