### ISSUE TITLE
Integration does not work if you have a bridge

### ISSUE THREAD

**Issue by andrsinha** [RobertD502/home-assistant-flair#77]
Upgrading to a bridge removes the ability to even see the puck temperatures.

**Comment by RobertD502** [comment]
Can you elaborate on what exactly you mean?

I have a bridge on my account and puck shows temperature:

![image](https://github.com/RobertD502/home-assistant-flair/assets/52541649/766edde8-786c-46a8-8eb2-862b0aa0acce)

![image](https://github.com/RobertD502/home-assistant-flair/assets/52541649/29064014-6649-4584-8f9e-84d1bebb91f3)

The support added for bridges in this integration does not touch any of the code related to pucks.

**Comment by andrsinha** [comment]
When you add a bridge you switch all your pick to be sensors and not gateways. That is the point of the bridge ; it give better coverage, stronger signal and takes over the gateway role. When you do this the temp read by the pucks becomes unavailable.  ![image](https://github.com/RobertD502/home-assistant-flair/assets/160545652/34a66ef3-a28c-43d0-be0f-44d054b8840c)

**Comment by RobertD502** [comment]
Just to clear something up: Adding a bridge to your Flair setup doesn't require you to switch pucks to become sensors instead of gateways. You have the option of converting any gateway pucks to be sensor pucks.

Could you please enable debug logging for the integration and post the log here. 

Based on your puck entities being unavailable, it is likely that Flair's API is reporting the puck as being offline, which results in the puck entities becoming unavailable. Once I look at the log, I'll know more.

**Comment by andrsinha** [comment]
I've turned on debugging. Where is it logged? 

I spoke to flair. The point of the bridge is to be the gateway to rule them all. If you have your pucks in gateway mode you dont need a bridge. Either way any puck in send r mode is unavailable.

**Comment by RobertD502** [comment]
Do this from a computer:

On the integrations page, click on the flair integration, and click on "enable debug logging". Once you have done that, the bug icon will become red. At this point, you need to restart Home Assistant. When Home Assistant is back up again, wait about a minute. Then go back to the integrations page, open the flair integration, and disable debug logging. At this point, Home Assistant will save a log file to your computer. Share that log file here.

I get what the point of the bridge is. I'm merely stating that it is not a hard requirement that you convert gateway pucks to sensor pucks when you add a bridge. Even when setting up the bridge, Flair lets you know that you can convert gateway pucks to sensor pucks, however, this is not something that you HAVE to do. I currently have both a puck and bridge acting as gateways.

**Comment by andrsinha** [comment]
There you go

[home-assistant_flair_2024-06-09T17-43-24.766Z.log](https://github.com/user-attachments/files/15753538/home-assistant_flair_2024-06-09T17-43-24.766Z.log)

**Comment by RobertD502** [comment]
![Offline Pucks](https://github.com/RobertD502/home-assistant-flair/assets/52541649/e12752cf-2d40-4db2-8537-4c86fade16e2)

All of those pucks seen in the image above are reported as being offline, as indicated by the `inactive` key reporting `true` (outlined in red). In addition, you can also tell by the `connected-gateway-id` key (outlined in blue) which is reported as null meaning that none of those pucks currently have an active connection to your gateway bridge. As a result of those pucks being reported as offline by the Flair API, the entities in Home Assistant appear as `unavailable`.

You will need to figure out why those pucks are offline and are not connecting to your Flair bridge gateway. You can attempt to run the network repair mode (found in the flair app under Home Settings --> Flair Devices --> Network Repair Mode). If you are unsuccessful, you will need to reach out to Flair for help as this is not related to/not a bug in the Flair integration.

**Comment by andrsinha** [comment]
Thanks for looking at this. Network repair did not fix it. It looks like the switch over to the bridge had problems and I have to add and remove individual pucks to reset everything.

Fair need diagnostic like yours!

On Jun 9, 2024, at 11:32 AM, Dr. Drinovac ***@***.***> wrote:



Offline.Pucks.png (view on web)<https://github.com/RobertD502/home-assistant-flair/assets/52541649/e12752cf-2d40-4db2-8537-4c86fade16e2>

All of those pucks seen in the image above are reported as being offline, as indicated by the inactive key reporting true (outlined in red). In addition, you can also tell by the connected-gateway-id key (outlined in blue) which is reported as null meaning that none of those pucks currently have an active connection to your gateway bridge. As a result of those pucks being reported as offline by the Flair API, the entities in Home Assistant appear as unavailable.

You will need to figure out why those pucks are offline and are not connecting to your Flair bridge gateway. You can attempt to run the network repair mode (found in the flair app under Home Settings --> Flair Devices --> Network Repair Mode). If you are unsuccessful, you will need to reach out to Flair for help as this is not related to/not a bug in the Flair integration.

**Comment by RobertD502** [comment]
If you use the Flair app, any vents or pucks that are offline should have a red dot next to them and/or say they are offline.

**Comment by andrsinha** [comment]
I do. They were online with strong signal then they started falling off. The network rebuild actually made it worse. Turns out I had some old out of data puck and some that just needed an update. A step by step rebuild has fixed all but one.

Thx

On Jun 9, 2024, at 15:36, Dr. Drinovac ***@***.***> wrote:

﻿

If you use the Flair app, any vents or pucks that are offline should have a red dot next to them and/or say they are offline.

**Comment by andrsinha** [comment]
Mystery solved. I have reached the limit of supported devices! I need a second bridge.
