### ISSUE TITLE
Integration climate entities (plus some others) not available.

### ISSUE THREAD

**Issue by Audio-Lefty** [RobertD502/home-assistant-flair#93]
Installed integration in November and worked perfectly. When I updated to  HA 2024.12 a number of entities became unavailable, in particular the climate (thermostat) entities.
Tried uninstalling and reinstalling.

Any suggestions?

I activiated debug logging and have attached text file.

[flair debug log.txt](https://github.com/user-attachments/files/18193139/flair.debug.log.txt)

**Comment by RobertD502** [comment]
Can you provide screenshots of the Flair "devices" in Home Assistant and point out the specific entities that your issue is with? This will help me focus in on the data within the debug log.

**Comment by Audio-Lefty** [comment]
Hi,Have attached some screen shots.Below is explanation of setup.Have 1 Flair Bridge 4 Flair Pucks.Each Puck in a roomRooms1. Andrea Bedroom - 1 vent2. Guest Bed Room - 1 vent3. Study - 1 vent4. Living - 4 vents (Living Left, Living Right, Kitchen, LandingIn each Device - Room - all 4 entities are unavailable.Device Pucks  1 entity unavailable (13 available) eg.  number.andrea_bedroom_temperature_calibrationDevice Vent  - all entities available - 8.Allan Rich0418 176 ***@***.*** 19 Dec 2024, at 4:58 PM, Dr. Drinovac ***@***.***> wrote:﻿
Can you provide screenshots of the Flair "devices" in Home Assistant and point out the specific entities that your issue is with? This will help me focus in on the data within the debug log.

**Comment by RobertD502** [comment]
Can you retry doing that on GitHub itself. Replying by email seems to have messed up formatting and no screenshots included.

**Comment by RobertD502** [comment]
But just to give you preliminary findings - all of your room climate entities are unavailable because your structure mode is set to manual according to the debug log. If you go to the flair app, you'll notice that you can't set a room temperature when your mode is Manual instead of Auto.

If you check the documentation on github, I make note of why the entity is unavailable in certain scenarios.

**Comment by RobertD502** [comment]
To you and yours as well!
